language: python
python:
  - "3.5"
services:
  - postgresql

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:25 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
  - psql -c 'create database itindublin_test;' -U postgres
install:
  - cp contrib/env-sample .env
  - sudo apt-get build-dep python-psycopg2
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - pip install -q -r requirements.txt
  - pip install psycopg2
script:
  - py.test --cov=service test/
after_success:
  coveralls
notifications:
  email: false