language: python
python:
  - "3.5"
services:
  - postgresql

before_script:
  - psql -c 'create database itindublin;' -U postgres

install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements.txt
script:
  - py.test --cov=service test/
after_success:
  coveralls
